[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.dev]
description = "Build"
workspace = false
command = "cargo"
args = ["shuttle", "run"]

[tasks.deploy_prod]
description = "Build"
workspace = false
command = "cargo"
args = ["shuttle", "deploy"]
