[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.dev]
description = "Build"
workspace = false
command = "cargo"
args = ["shuttle", "run"]

[tasks.deploy_local]
description = "deploy binary file for "
workspace = false
script = ['''
#!/usr/bin/env bash
rm -f ~/bin/tsundoku-accelerator/backend-cli
cp -p ./target/release/backend-cli ~/bin/tsundoku-accelerator/
''']
dependencies = ["compile_release"]
